plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url = "https://maven.fabricmc.net/" }
	maven { url = "https://maven.blamejared.com" }
}

loom {
	mods {
		"ironfurnaces" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${loader_version}"

	implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

	compileOnly "org.jetbrains:annotations:26.0.2"

	compileOnly "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"
	localRuntime "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand(
			"version": inputs.properties.version,
			"mod_id": project.mod_id,
			"mod_name": project.mod_name,
			"mod_license": project.mod_license,
			"mod_authors": project.mod_authors,
			"mod_description": project.mod_description
		)
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}" }
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
	repositories {
	}
}
